### ISSUE TITLE
windows报错无法使用

### ISSUE THREAD

**Issue by iven13465** [noneplugin/nonebot-plugin-shindan#14]
![GW@J2R~IZK(C3~7P XLS 8M](https://user-images.githubusercontent.com/95957360/208116230-073d70d0-a294-496f-941a-dc75cbf77eb4.png)
按照https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/25 上面的方法在配置了.env中配置了 ```FASTAPI_RELOAD=false``` 也没有用，想问一下如何才能在windows上使用这款插件

**Comment by MeetWq** [comment]
检查一下.env.dev里有没有FASTAPI_RELOAD

**Comment by iven13465** [comment]
![G(`F3J7_R5$@E BZ7C6}6 U](https://user-images.githubusercontent.com/95957360/208215838-e68fcd25-5214-4aa0-a743-64a3315732f9.png)
![(D6DPL13L%72ONM X%C%QGJ](https://user-images.githubusercontent.com/95957360/208215840-f383b815-4566-426a-b039-f0d3c60e4fcf.png)
有的，但依然是同一个报错

**Comment by MeetWq** [comment]
暂时看不出是什么问题，你把从启动到报错的所有日志贴出来看看

**Comment by iven13465** [comment]
```E:\bot\1>nb run
12-17 10:24:43 [SUCCESS] nonebot | NoneBot is initializing...
12-17 10:24:43 [INFO] nonebot | Current Env: dev
12-17 10:24:44 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_aidraw"
12-17 10:24:44 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-17 10:24:44 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
12-17 10:24:44 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_chatgpt"
12-17 10:24:45 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_shindan"
12-17 10:24:45 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_remake"
12-17 10:24:45 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_simplemusic"
12-17 10:24:45 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_picstatus"
12-17 10:24:45 [SUCCESS] nonebot | Succeeded to import "nonebot-plugin-bangumi-search"
12-17 10:24:45 [SUCCESS] nonebot | Succeeded to import "1"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "alapi"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "quotations"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "pr2"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "d2joke"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "help"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "blacklist"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "setu"
12-17 10:24:46 [SUCCESS] nonebot | Succeeded to import "get_wife"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "group_mem_notice"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "genshin_role_card"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "genshin_equip_recommand"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "hanjian"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "jianshang"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "fd"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "moegoe"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "bt"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "what_anime"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "touziji"
12-17 10:24:47 [SUCCESS] nonebot | Succeeded to import "face_beauty"
12-17 10:24:49 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gamedraw"
12-17 10:24:51 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
12-17 10:24:51 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
12-17 10:24:52 [SUCCESS] nonebot | Succeeded to import "bot_manager"
12-17 10:24:52 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
12-17 10:24:52 [SUCCESS] nonebot | Succeeded to import "Mihoyo_bbs"
12-17 10:24:52 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
12-17 10:24:53 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
12-17 10:24:53 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
12-17 10:24:53 [SUCCESS] nonebot | Succeeded to import "plugin_manager"
12-17 10:24:55 [SUCCESS] nonebot | Succeeded to import "Learning_Chat"
12-17 10:24:55 [SUCCESS] nonebot | Succeeded to import "tools"
12-17 10:24:58 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
12-17 10:24:58 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
12-17 10:24:58 [SUCCESS] nonebot | Succeeded to import "news60s"
12-17 10:24:58 [SUCCESS] nonebot | Succeeded to import "Paimon_Abyss"
12-17 10:24:59 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
12-17 10:24:59 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
12-17 10:24:59 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
12-17 10:24:59 [SUCCESS] nonebot | Succeeded to import "LittlePaimon"
12-17 10:24:59 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_pixivrank_search"
Matplotlib is building the font cache; this may take a moment.
12-17 10:25:05 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_imageutils"
12-17 10:25:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_petpet"
12-17 10:25:12 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_russian"
12-17 10:25:13 [WARNING] nonebot | Duplicated prefix rule "搜图"
12-17 10:25:13 [WARNING] nonebot | Duplicated prefix rule "/搜图"
12-17 10:25:13 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_hikarisearch"
12-17 10:25:13 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_withdraw"
12-17 10:25:13 [WARNING] nonebot | Duplicated prefix rule "早安"
12-17 10:25:13 [WARNING] nonebot | Duplicated prefix rule "/早安"
12-17 10:25:13 [WARNING] nonebot | Duplicated prefix rule "晚安"
12-17 10:25:13 [WARNING] nonebot | Duplicated prefix rule "/晚安"
12-17 10:25:13 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_morning"
12-17 10:25:14 [SUCCESS] nonebot_plugin_word_bank2 | 读取词库位于 E:\bot\1\data\word_bank\bank.json
12-17 10:25:14 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_word_bank2"
12-17 10:25:14 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_charpic"
12-17 10:25:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_randomtkk"
12-17 10:25:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_fortune"
12-17 10:25:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_localstore"
12-17 10:25:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_datastore"
12-17 10:25:15 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_chatrecorder"
12-17 10:25:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_wordcloud"
12-17 10:25:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_ddcheck"
12-17 10:25:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_asoulcnki"
12-17 10:25:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_miragetank"
12-17 10:25:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_manager"
12-17 10:25:16 [WARNING] nonebot | Duplicated prefix rule "占卜"
12-17 10:25:16 [WARNING] nonebot | Duplicated prefix rule "/占卜"
12-17 10:25:16 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_tarot"
12-17 10:25:17 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_weather_lite"
12-17 10:25:17 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_bilibili_viode"
12-17 10:25:17 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_pixiv"
12-17 10:25:17 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_smart_reply"
12-17 10:25:18 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_bottle"
12-17 10:25:18 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_RealESRGAN"
12-17 10:25:18 [INFO] nonebot_bison | Nonebot test frontend will be running at: http://localhost:25532/bison/
12-17 10:25:18 [SUCCESS] nonebot | Succeeded to import "nonebot_bison"
12-17 10:25:18 [SUCCESS] nonebot | Running NoneBot...
12-17 10:25:18 [INFO] uvicorn | Started server process [15020]
12-17 10:25:18 [INFO] uvicorn | Waiting for application startup.
12-17 10:25:18 [INFO] nonebot_plugin_apscheduler | Scheduler Started
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at E:\py\Lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "E:\py\Lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "E:\py\Lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "E:\py\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "E:\py\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "E:\py\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "E:\py\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
12-17 10:25:18 [ERROR] uvicorn | Traceback (most recent call last):
  File "E:\py\Lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "E:\py\Lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "E:\py\Lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "E:\py\Lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "E:\py\Lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 60, in get_browser
    return _browser or await init(**kwargs)
  File "E:\py\Lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 36, in init
    _playwright = await async_playwright().start()
  File "E:\py\Lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "E:\py\Lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "E:\py\Lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "E:\py\Lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "E:\py\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "E:\py\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "E:\py\lib\asyncio\base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "E:\py\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

12-17 10:25:18 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by iven13465** [comment]
已用poetry虚拟环境启动解决
