### ISSUE TITLE
发送占卜指令直接返回：出错了，请稍后再试

### ISSUE THREAD

**Issue by RainbowDashKira** [noneplugin/nonebot-plugin-shindan#19]
![7I4 `NZ }WQ28){@AT4L}1Y](https://user-images.githubusercontent.com/117131527/231323518-1f9c7d46-998f-4bda-830c-759a3c83b93e.png)

以前没问题，今天突然就这样了。所有指令都不行。

**Comment by xi-yue-233** [comment]
一样

**Comment by Cvandia** [comment]
一样

**Comment by ElaineOwO** [comment]
我也是 
04-12 15:51:52 [WARNING] nonebot_plugin_shindan | Traceback (most recent call last):
  File "C:\Users\yilin\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_shindan\__init__.py", line 218, in _
    res = await make_shindan(id, name, mode)
  File "C:\Users\yilin\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_shindan\shindanmaker.py", line 83, in make_shindan
    html, has_chart = await render_html(content)
  File "C:\Users\yilin\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_shindan\shindanmaker.py", line 113, in render_html
    assert isinstance(result, Tag)
AssertionError

**Comment by MeetWq** [comment]
fix in db6a6af7cd8a59b701e23f6a439a62dd5ce29d5b
