### ISSUE TITLE
启动nb时候提示必须指定一个数据库

### ISSUE THREAD

**Issue by ElaineOwO** [noneplugin/nonebot-plugin-shindan#35]
01-04 01:21:04 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\starlette\routing.py", line 705, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\BOT\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 156, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 41, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 35, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot_plugin_orm\__init__.py", line 77, in init_orm
    _init_orm()
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot_plugin_orm\__init__.py", line 99, in _init_orm
    _init_engines()
  File "C:\Users\BOT\Desktop\BOT\xyl\.venv\lib\site-packages\nonebot_plugin_orm\__init__.py", line 196, in _init_engines
    raise ValueError(
ValueError: 必须指定一个默认数据库 (SQLALCHEMY_DATABASE_URL 或 SQLALCHEMY_BINDS[""]). 可以通过 `pip install nonebot-plugin-orm[default]` 获得开箱即用的数据库配置.

安装了pip install nonebot-plugin-orm[default]也还是不行。。要怎么手动指定数据库呢。。自己是小白用户不太懂

**Comment by ElaineOwO** [comment]
bot是安装在虚拟环境里的，看到orm也作为依赖一起安装了，，要改怎么配置呢

**Comment by ElaineOwO** [comment]
我是baka 安装了半天安装到虚拟环境外面去了QAQ
