### ISSUE TITLE
插件冲突问题

### ISSUE THREAD

**Issue by LMUFC** [noneplugin/nonebot-plugin-shindan#44]
bot主体用的zhenxun_bot，应该是nonebot_plugin_uninfo重复导入的问题，但不知道如何修改，求指导。

10-16 14:18:00 [ERROR] nonebot | Failed to import "nonebot_plugin_uninfo"
Traceback (most recent call last):
  File "/root/zhenxun_bot/bot.py", line 32, in <module>
    nonebot.load_plugin("nonebot_plugin_shindan")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot_plugin_shindan/__init__.py", line 16, in <module>
    require("nonebot_plugin_uninfo")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 185, in require
    plugin = load_plugin(name)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 182, in load_plugin
    raise RuntimeError(
RuntimeError: Module nonebot_plugin_uninfo is not loaded as a plugin! Make sure not to import it before loading.
10-16 14:18:00 [ERROR] nonebot | Failed to import "nonebot_plugin_shindan"
Traceback (most recent call last):
  File "/root/zhenxun_bot/bot.py", line 32, in <module>
    nonebot.load_plugin("nonebot_plugin_shindan")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot_plugin_shindan/__init__.py", line 16, in <module>
    require("nonebot_plugin_uninfo")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 188, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_uninfo"!

**Comment by LMUFC** [comment]
已解决，直接clone到插件文件夹导入，然后根据pull request里面的修改下就可以用了

**Comment by TrinityLeaves** [comment]
> 已解决，直接clone到插件文件夹导入，然后根据pull request里面的修改下就可以用了

兄弟我也是一样的问题，重新导入插件不行啊，pull request那个是哪个啊
